<?php

/**
 * Texts used in the application.
 * These texts are used via Text::get('FEEDBACK_USERNAME_ALREADY_TAKEN').
 * Could be extended to i18n etc.
 */
return array(
    "FEEDBACK_UNKNOWN_ERROR" => "Unknown error occurred!",
    "FEEDBACK_DELETED" => "Your account has been deleted.",
    "FEEDBACK_ACCOUNT_SUSPENDED" => "Account Suspended for ",
    "FEEDBACK_ACCOUNT_SUSPENSION_DELETION_STATUS" => "This user's suspension / deletion status has been edited.",
    "FEEDBACK_ACCOUNT_CANT_DELETE_SUSPEND_OWN" => "You can not delete or suspend your own account.",
    "FEEDBACK_ACCOUNT_USER_SUCCESSFULLY_KICKED" => "The selected user has been successfully kicked out of the system (by resetting this user's session)",
    "FEEDBACK_PASSWORD_WRONG_3_TIMES" => "You have typed in a wrong password 3 or more times already. Please wait 30 seconds to try again.",
    "FEEDBACK_ACCOUNT_NOT_ACTIVATED_YET" => "Your account is not activated yet. Please click on the confirm link in the mail.",
    "FEEDBACK_USERNAME_OR_PASSWORD_WRONG" => "Usuario y contraseña incorrecto. Intentar de nuevo.",
    "FEEDBACK_USER_DOES_NOT_EXIST" => "Usuario no existe.",
    "FEEDBACK_LOGIN_FAILED" => "Login failed.",
    "FEEDBACK_LOGIN_FAILED_3_TIMES" => "Login failed 3 or more times already. Please wait 30 seconds to try again.",
    "FEEDBACK_USERNAME_FIELD_EMPTY" => "Campo usuario vacio.",
    "FEEDBACK_PASSWORD_FIELD_EMPTY" => "Campo contraseña vacio.",
    "FEEDBACK_USERNAME_OR_PASSWORD_FIELD_EMPTY" => "Campo usuario y/o contraseña vacio.",
    "FEEDBACK_USERNAME_EMAIL_FIELD_EMPTY" => "Campo Usuario/Correo esta vacio.",
    "FEEDBACK_EMAIL_FIELD_EMPTY" => "Email field was empty.",
    "FEEDBACK_EMAIL_REPEAT_WRONG" => "Email and email repeat are not the same",
    "FEEDBACK_EMAIL_AND_PASSWORD_FIELDS_EMPTY" => "Email and password fields were empty.",
    "FEEDBACK_USERNAME_SAME_AS_OLD_ONE" => "Sorry, that username is the same as your current one. Please choose another one.",
    "FEEDBACK_USERNAME_ALREADY_TAKEN" => "Sorry, that username is already taken. Please choose another one.",
    "FEEDBACK_USER_EMAIL_ALREADY_TAKEN" => "Sorry, that email is already in use. Please choose another one.",
    "FEEDBACK_USERNAME_CHANGE_SUCCESSFUL" => "Your username has been changed successfully.",
    "FEEDBACK_USERNAME_AND_PASSWORD_FIELD_EMPTY" => "Username and password fields were empty.",
    "FEEDBACK_USERNAME_DOES_NOT_FIT_PATTERN" => "Username does not fit the name pattern: only a-Z and numbers are allowed, 2 to 64 characters.",
    "FEEDBACK_EMAIL_DOES_NOT_FIT_PATTERN" => "Sorry, your chosen email does not fit into the email naming pattern.",
    "FEEDBACK_EMAIL_SAME_AS_OLD_ONE" => "Sorry, that email address is the same as your current one. Please choose another one.",
    "FEEDBACK_EMAIL_CHANGE_SUCCESSFUL" => "Your email address has been changed successfully.",
    "FEEDBACK_CAPTCHA_WRONG" => "The entered captcha security characters were wrong.",
    "FEEDBACK_PASSWORD_REPEAT_WRONG" => "Password and password repeat are not the same.",
    "FEEDBACK_PASSWORD_TOO_SHORT" => "Password has a minimum length of 6 characters.",
    "FEEDBACK_USERNAME_TOO_SHORT_OR_TOO_LONG" => "Username cannot be shorter than 2 or longer than 64 characters.",
    "FEEDBACK_ACCOUNT_SUCCESSFULLY_CREATED" => "Your account has been created successfully and we have sent you an email. Please click the VERIFICATION LINK within that mail.",
    "FEEDBACK_VERIFICATION_MAIL_SENDING_FAILED" => "Sorry, we could not send you an verification mail. Your account has NOT been created.",
    "FEEDBACK_ACCOUNT_CREATION_FAILED" => "Sorry, your registration failed. Please go back and try again.",
    "FEEDBACK_VERIFICATION_MAIL_SENDING_ERROR" => "Verification mail could not be sent due to: ",
    "FEEDBACK_VERIFICATION_MAIL_SENDING_SUCCESSFUL" => "A verification mail has been sent successfully.",
    "FEEDBACK_ACCOUNT_ACTIVATION_SUCCESSFUL" => "Activation was successful! You can now log in.",
    "FEEDBACK_ACCOUNT_ACTIVATION_FAILED" => "Sorry, no such id/verification code combination here! It might be possible that your mail provider (Yahoo? Hotmail?) automatically visits links in emails for anti-scam scanning, so this activation link might been clicked without your action. Please try to log in on the main page.",
    "FEEDBACK_AVATAR_UPLOAD_SUCCESSFUL" => "Avatar upload was successful.",
    "FEEDBACK_AVATAR_UPLOAD_WRONG_TYPE" => "Only JPEG and PNG files are supported.",
    "FEEDBACK_AVATAR_UPLOAD_TOO_SMALL" => "Avatar source file's width/height is too small. Needs to be 100x100 pixel minimum.",
    "FEEDBACK_AVATAR_UPLOAD_TOO_BIG" => "Avatar source file is too big. 5 Megabyte is the maximum.",
    "FEEDBACK_AVATAR_FOLDER_DOES_NOT_EXIST_OR_NOT_WRITABLE" => "Avatar folder does not exist or is not writable. Please change this via chmod 775 or 777.",
    "FEEDBACK_AVATAR_IMAGE_UPLOAD_FAILED" => "Something went wrong with the image upload.",
    "FEEDBACK_AVATAR_IMAGE_DELETE_SUCCESSFUL" => "You successfully deleted your avatar.",
    "FEEDBACK_AVATAR_IMAGE_DELETE_NO_FILE" => "You don't have a custom avatar.",
    "FEEDBACK_AVATAR_IMAGE_DELETE_FAILED" => "Something went wrong while deleting your avatar.",
    "FEEDBACK_PASSWORD_RESET_TOKEN_FAIL" => "Could not write token to database.",
    "FEEDBACK_PASSWORD_RESET_TOKEN_MISSING" => "No password reset token.",
    "FEEDBACK_PASSWORD_RESET_MAIL_SENDING_ERROR" => "Password reset mail could not be sent due to: ",
    "FEEDBACK_PASSWORD_RESET_MAIL_SENDING_SUCCESSFUL" => "A password reset mail has been sent successfully.",
    "FEEDBACK_PASSWORD_RESET_LINK_EXPIRED" => "Your reset link has expired. Please use the reset link within one hour.",
    "FEEDBACK_PASSWORD_RESET_COMBINATION_DOES_NOT_EXIST" => "Username/Verification code combination does not exist.",
    "FEEDBACK_PASSWORD_RESET_LINK_VALID" => "Password reset validation link is valid. Please change the password now.",
    "FEEDBACK_PASSWORD_CHANGE_SUCCESSFUL" => "Password successfully changed.",
    "FEEDBACK_PASSWORD_CHANGE_FAILED" => "Sorry, your password changing failed.",
    "FEEDBACK_PASSWORD_NEW_SAME_AS_CURRENT" => "New password is the same as the current password.",
    "FEEDBACK_PASSWORD_CURRENT_INCORRECT" => "Current password entered was incorrect.",
    "FEEDBACK_ACCOUNT_TYPE_CHANGE_SUCCESSFUL" => "Account type change successful",
    "FEEDBACK_ACCOUNT_TYPE_CHANGE_FAILED" => "Account type change failed",
    "FEEDBACK_NOTE_CREATION_FAILED" => "Note creation failed.",
    "FEEDBACK_NOTE_EDITING_FAILED" => "Note editing failed.",
    "FEEDBACK_NOTE_DELETION_FAILED" => "Note deletion failed.",
    "FEEDBACK_COOKIE_INVALID" => "Your remember-me-cookie is invalid.",
    "FEEDBACK_COOKIE_LOGIN_SUCCESSFUL" => "You were successfully logged in via the remember-me-cookie.",
	
	"FEEDBACK_SOLICITUD_ACTUALIZADA_EXITO" => "Solicitud actualizada con éxito",
	"FEEDBACK_SOLICITUD_AGREGADA_EXITO" => "Solicitud agregada con éxito",
	"FEEDBACK_SERVICIO_AGREGADO_EXITO" => "Servicio agregado con éxito",
	"FEEDBACK_SERVICIO_ELIMINADO_EXITO" => "Servicio eliminado con éxito",
	"FEEDBACK_SERVICIO_ACTUALIZADO_EXITO" => "Servicio actualizado con éxito",
	"FEEDBACK_VIAJERO_AGREGADO_EXITO" => "Viajero agregado con éxito",
	"FEEDBACK_VIAJERO_ACTUALIZADO_EXITO" => "Viajero actualizado con éxito",
	"FEEDBACK_VIAJERO_VALIDADO_EXITO" => "Viajero validado con éxito",
	"FEEDBACK_SOLICITUD_REASIGNADA_EXITO" => "Solicitud asignada con éxito",
	"FEEDBACK_SOLICITUD_ASIGNADA_EXITO" => "Solicitud asignada con éxito",
	"FEEDBACK_SOLICITUD_TOMADA_EXITO" => "Solicitud tomada con éxito",
	"FEEDBACK_SOLICITUD_ASIGNADA_PREVIAMENTE" => "Solicitud asignada previamente",
	"FEEDBACK_SOLICITUD_CANCELADA_EXITO" => "Solicitud cancelada con éxito",
	"FEEDBACK_SOLICITUD_REALIZADA_EXITO" => "Solicitud realizada con éxito",
	"FEEDBACK_CLIENTE_PREVIAMENTE_REGISTRADO" => "Prospecto previamente registrado",
	"FEEDBACK_CAMPO_CORREO_TELEFONO_WHATSAPP_VACIO" => "Debe proporcionar un correo, teléfono o whatsapp por lo menos",
	"FEEDBACK_CONFIRMACION_CORREO_NO_COINCIDE" => "Confirmación de correo electrónico no coincide con correo electrónico",
	"FEEDBACK_FORMATO_CORREO_NO_VALIDO" => "Formato de correo electrónico no válido",
	"FEEDBACK_CAMPO_FUENTE_VACIO" => "Campo fuente obligatorio",
	"FEEDBACK_COTIZACION_AGREGADA_EXITO" => "Cotización agregada con éxito",
	"FEEDBACK_COTIZACION_MANUAL_AGREGADA_EXITO" => "Cotización manual agregada con éxito",
	"FEEDBACK_RESERVACION_COMPARTIDA_EXITO" => "Reservación compartida con éxito",
	"FEEDBACK_RESERVACION_AGREGADA_EXITO" => "Reservación agregada con éxito",
	"FEEDBACK_RESERVACION_ELIMINADA_EXITO" => "Reservación eliminada con éxito",
	"FEEDBACK_RESERVACION_PORCONFIRMAR_EXITO" => "Reservación por confirmar con éxito",
	"FEEDBACK_RESERVACION_ACTUALIZADA_EXITO" => "Reservación actualizada con éxito",
	"FEEDBACK_RESERVACION_VALIDADA_EXITO" => "Reservación validada con éxito",
	"FEEDBACK_PAGO_REPORTADO_EXITO" => "Pago reportado con éxito",
	"FEEDBACK_PAGO_APLICADO_EXITO" => "Pago aplicado con éxito",
	"FEEDBACK_REFERENCIA_PAGO_DUPLICADA" => "Referencia pago duplicada",
	"FEEDBACK_SERVICIO_ESTATUS_ACTUALIZADO_EXITO" => "Estatus de servicio actualizado con éxito",
	"FEEDBACK_GASTO_REPORTADO_EXITO" => "Gasto reportado con éxito",
	"FEEDBACK_GASTO_ACTUALIZADO_EXITO" => "Gasto actualizado con éxito",
	"FEEDBACK_PAGO_REPORTADO_CLIENTE_EXITO" => "¡Gracias por su pago oportuno! Su pago será validado en breve por nuestro departamento contable y se enviará automáticamente el recibo de pago a su correo ingresado.",
	"FEEDBACK_TOTALES_RESERVACION_ACTUALIZADA_EXITO" => "Totales Reservación actualizados con éxito",
	"FEEDBACK_COMPRA_REPORTADA_EXITO" => "Compra reportada con éxito",
	"FEEDBACK_COMPRA_ACTUALIZADA_EXITO" => "Compra actualizada con éxito",
	"FEEDBACK_RECOLECCION_REALIZADA_EXITO" => "Recolección efectivo realizada con éxito",
	"FEEDBACK_CORTE_EGRESOS_GENERADO_EXITO" => "Corte ciego de salidas generado con éxito",
	"FEEDBACK_CORTE_INGRESOS_GENERADO_EXITO" => "Corte ciego de entradas generado con éxito",
	
	
);
